* Toma-what?

  Tomatinho! The [[https://github.com/konr/tomatinho][Emacs pomodoro timer]] now on android! https://play.google.com/store/apps/details?id=com.tomatinho_mobile
  
* How to compile and run it in your phone

  1. Build the .js files from the ClojureScript (lein cljs once prod)
  2. Link the resources directory to the assets directory (ls -s resources/public/ android/assets/www/)
  3. Go to the android directory (cd android)
  4. Plug your device, making sure you have:
     (1) USB debugging enabled on the phone
     (2) Android tools (such as adb)
  5. Install it! (ant debug install)

* To be done

 - [ ] Advanced compilation mode
 - [ ] Fast clicks, as in https://developers.google.com/mobile/articles/fast_buttons


* External stuff

  The app icon I got from iconicon.net, with the following license:

  By using stock icons downloaded from Icon Icon, you agree to the
  following: All ownership and copyright of the stock icons remains the
  property of Steven Ansell. You may not resell or redistribute the
  icons in any way beyond licensed use in your products according to the
  terms of the license. All stock icons are provided “As is.” You agree
  not to hold Steven Ansell liable for any damage that may occur as a
  result of using the stock icons. Stock icons downloaded from Icon Icon
  may be used by you in an unlimited number of software or internet
  products. You may also display the stock icons in documentation, help
  files, and advertising materials that pertain to these products. You
  are free to sell and distribute your products that utilize Steven
  Ansell’s stock icons without further royalty due to Steven Ansell.
